### ISSUE TITLE
去淘宝看看香薰

### ISSUE THREAD

**Issue by qifengle1998** [qifengle1998/LifeTime#99]
# 3.进入状态方法
- 通过一些机械性的、互动性强的（但不能过分偏向娱乐）的事物，让自己先动起来：比如 抄书、单词互动游戏
- 善用纯音乐和香薰，让自己进入学习状态

# 参考
[如何快速进入高效状态｜怎样学到上头｜5分钟掌握高效小妙招_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV12Z4y1s7o6?spm_id_from=333.337.search-card.all.click&vd_source=267912aeeecbd49d6471a2aabb11aaec)

_Originally posted by @qifengle1998 in https://github.com/qifengle1998/LifeTime/issues/2#issuecomment-1166996174_

**Comment by qifengle1998** [comment]
[20款无火香薰测评！_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV19o4y1C7ec?spm_id_from=333.337.search-card.all.click&vd_source=267912aeeecbd49d6471a2aabb11aaec)
根据这个视频，花了31.5 买了名创优品 的血橙与雪松 香薰

**Comment by yuyuyu-github** [comment]
![8DFE9C598F0DBD423E43FE23AE3353E0](https://user-images.githubusercontent.com/37429029/176990725-171e43e4-b144-4570-9aca-c6361816336c.jpg)
